import{FilesetResolver,PoseLandmarker}from"https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm";
const $=id=>document.getElementById(id),video=$("camera"),canvas=$("overlay"),ctx=canvas.getContext("2d"),start=$("startButton"),capture=$("captureButton"),switchBtn=$("switchButton"),guideBtn=$("guideButton"),permission=$("permissionScreen"),ai=$("aiStatus"),people=$("peopleStatus"),banner=$("successBanner"),bannerTitle=$("successTitle"),bannerSub=$("successSub"),countdown=$("countdown"),poseName=$("poseName"),poseHint=$("poseHint"),poseIcon=$("poseIcon"),progressCircle=$("progressCircle"),progressText=$("progressText"),resultDialog=$("resultDialog"),resultImage=$("resultImage"),metricsDialog=$("metricsDialog"),metricGrid=$("metricGrid"),poseMetrics=$("poseMetrics"),toast=$("toast");
const model="https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/latest/pose_landmarker_lite.task",wasm="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm";
const P={heart:{n:"손하트",i:"♡",h:"두 손을 머리 위에서 모아 하트를 만들어보세요.",ms:600,t:"619와 하트 성공!",s:"초록 캐릭터와 하트가 터집니다"},jump:{n:"점프",i:"↟",h:"전신이 보이게 선 뒤, 살짝 앉았다가 점프하세요.",ms:80,t:"함께 날아올랐어요!",s:"고글 캐릭터와 별빛 점프"},mimic:{n:"캐릭터 따라 하기",i:"☆",h:"양팔과 두 다리를 넓게 펴 별 모양을 만들어보세요.",ms:600,t:"FYF 싱크로율 100%!",s:"좀비 캐릭터의 오라가 켜집니다"},highfive:{n:"하이파이브",i:"✋",h:"두 사람이 화면에 들어와 손을 높이 맞대보세요.",ms:380,t:"팀워크 폭발!",s:"빨간 모자와 619가 함께 등장합니다"},family:{n:"가족·단체 포즈",i:"♧",h:"두 명 이상이 함께 들어와 모두 한 손을 높이 들어주세요.",ms:700,t:"애니로드 크루 완성!",s:"네 캐릭터와 축하 파티가 열립니다"}};
const src={green:"./assets/green.svg?v=2",red:"./assets/red.svg?v=2",goggles:"./assets/goggles.svg?v=2",zombie:"./assets/zombie.svg?v=2"},chars=Object.fromEntries(Object.entries(src).map(([k,v])=>{const im=new Image();im.src=v;im.decoding="async";return[k,im]})),charsReady=Promise.all(Object.values(chars).map(im=>im.decode?.().catch(()=>{})||Promise.resolve()));
const C=[[11,13],[13,15],[12,14],[14,16],[11,12],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28]];
let landmarker,stream,running=false,front=true,guide=true,mode="heart",poses=[],lastTime=-1,lastInfer=0,holdAt=0,cool=0,effect=null,shotBlob=null,shotUrl=null,baseHip=null,crouchAt=0,prevHip=null,capturing=false;
const key="aniroadPoseStats",fresh=()=>({sessions:0,starts:0,success:0,captures:0,shares:0,downloads:0,byPose:Object.fromEntries(Object.keys(P).map(k=>[k,0])),events:[]});
let stats=(()=>{try{const s=JSON.parse(localStorage.getItem(key)||"{}");return{...fresh(),...s,byPose:{...fresh().byPose,...(s.byPose||{})},events:Array.isArray(s.events)?s.events:[]}}catch{return fresh()}})();stats.sessions++;save("session");
function save(type,data={}){if(type){stats.events.push({time:new Date().toISOString(),type,pose:mode,...data});if(stats.events.length>500)stats.events.shift()}try{localStorage.setItem(key,JSON.stringify(stats))}catch{}}
function note(msg){toast.textContent=msg;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2300)}
function status(text,state=""){ai.className=`status-pill ${state}`;ai.innerHTML=`<i></i>${text}`}
function visible(p,min=.42){return!!p&&(p.visibility??1)>=min&&(p.presence??1)>=min}
function dist(a,b){return a&&b?Math.hypot(a.x-b.x,a.y-b.y):99}
function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function angle(a,b,c){const x1=a.x-b.x,y1=a.y-b.y,x2=c.x-b.x,y2=c.y-b.y,d=Math.hypot(x1,y1)*Math.hypot(x2,y2);return d?Math.acos(Math.max(-1,Math.min(1,(x1*x2+y1*y2)/d)))*180/Math.PI:0}
function area(p){const q=p.filter(x=>visible(x));if(!q.length)return 0;const xs=q.map(x=>x.x),ys=q.map(x=>x.y);return(Math.max(...xs)-Math.min(...xs))*(Math.max(...ys)-Math.min(...ys))}
function mainPose(){return[...poses].sort((a,b)=>area(b)-area(a))[0]}
function setProgress(v){v=Math.max(0,Math.min(1,v));progressCircle.style.strokeDashoffset=113.1*(1-v);progressText.textContent=`${Math.round(v*100)}%`}
function select(k,user=true){mode=k;holdAt=0;baseHip=prevHip=null;crouchAt=0;document.querySelectorAll(".pose-tab").forEach(b=>b.classList.toggle("active",b.dataset.pose===k));poseName.textContent=P[k].n;poseHint.textContent=P[k].h;poseIcon.textContent=P[k].i;setProgress(0);if(user)save("pose_selected")}
document.querySelectorAll(".pose-tab").forEach(b=>b.onclick=()=>select(b.dataset.pose));
async function initAI(){status("AI·캐릭터 불러오는 중","loading");const files=await FilesetResolver.forVisionTasks(wasm),options=d=>({baseOptions:{modelAssetPath:model,delegate:d},runningMode:"VIDEO",numPoses:4,minPoseDetectionConfidence:.5,minPosePresenceConfidence:.5,minTrackingConfidence:.45});try{landmarker=await PoseLandmarker.createFromOptions(files,options("GPU"))}catch{landmarker=await PoseLandmarker.createFromOptions(files,options("CPU"))}await charsReady;status("AI + 캐릭터 준비 완료")}
async function startCamera(){stream?.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:front?"user":"environment"},width:{ideal:960},height:{ideal:720},frameRate:{ideal:24,max:30}}});video.srcObject=stream;await new Promise(r=>video.readyState>=1?r():video.onloadedmetadata=r);await video.play();resize();video.classList.toggle("mirrored",front);canvas.classList.toggle("mirrored",front)}
async function begin(){start.disabled=true;start.textContent="준비 중…";try{await Promise.all([initAI(),startCamera()]);permission.classList.add("dismissed");[capture,switchBtn,guideBtn].forEach(b=>b.disabled=false);running=true;stats.starts++;save("camera_started");requestAnimationFrame(loop)}catch(e){console.error(e);status("시작 오류","error");note(e.name==="NotAllowedError"?"카메라 권한을 허용해주세요.":"실행하지 못했습니다. 네트워크를 확인해주세요.");start.disabled=false;start.textContent="다시 시도하기"}}
function resize(){const w=video.videoWidth||720,h=video.videoHeight||960;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
function heart(p){if(!p)return 0;const[n,ls,rs,le,re,lw,rw]=[p[0],p[11],p[12],p[13],p[14],p[15],p[16]];if(![n,ls,rs,le,re,lw,rw].every(visible))return 0;const sw=dist(ls,rs),close=1-Math.min(1,dist(lw,rw)/Math.max(.12,sw*1.15)),high=Math.max(0,Math.min(1,(n.y+.12-(lw.y+rw.y)/2)/.18)),out=Math.max(0,Math.min(1,(dist(le,re)-dist(lw,rw))/Math.max(.08,sw)));return close*.43+high*.38+out*.19}
function mimic(p){if(!p)return 0;const[ls,rs,le,re,lw,rw,lh,rh,la,ra]=[p[11],p[12],p[13],p[14],p[15],p[16],p[23],p[24],p[27],p[28]];if(![ls,rs,le,re,lw,rw,lh,rh,la,ra].every(visible))return 0;return Math.min(1,(Math.min(angle(ls,le,lw),angle(rs,re,rw))/180)*.32+Math.min(1,dist(lw,rw)/(dist(ls,rs)*2.6))*.32+(1-Math.min(1,Math.abs(lw.y-ls.y)+Math.abs(rw.y-rs.y)))*.18+Math.min(1,dist(la,ra)/(dist(lh,rh)*2.2))*.18)}
function jump(p,now){if(!p)return 0;const[lh,rh,lk,rk,la,ra]=[p[23],p[24],p[25],p[26],p[27],p[28]];if(![lh,rh,lk,rk,la,ra].every(x=>visible(x,.35)))return 0;const hip=(lh.y+rh.y)/2,knee=(angle(lh,lk,la)+angle(rh,rk,ra))/2;if(baseHip==null)baseHip=hip;const velocity=prevHip==null?0:prevHip-hip;prevHip=hip;if(knee<145&&hip>baseHip+.008)crouchAt=now;const hit=now-crouchAt<1700&&baseHip-hip>.035&&velocity>.003;if(knee>=145&&!hit&&Math.abs(hip-baseHip)<.06)baseHip=baseHip*.985+hip*.015;return hit?1:knee<145?.55:Math.max(0,Math.min(.45,(baseHip-hip)/.07))}
function contact(){if(poses.length<2)return null;let best;for(let i=0;i<poses.length;i++)for(let j=i+1;j<poses.length;j++)for(const a of[poses[i][15],poses[i][16]])for(const b of[poses[j][15],poses[j][16]])if(visible(a)&&visible(b)){const d=dist(a,b);if(!best||d<best.d)best={d,p:mid(a,b)}}return best}
function highfive(){const c=contact();return c?Math.max(0,Math.min(1,1-c.d/.13)):0}
function family(){if(poses.length<2)return 0;const valid=poses.filter(p=>visible(p[11],.35)&&visible(p[12],.35));if(valid.length<2)return 0;const raised=valid.filter(p=>{const y=(p[11].y+p[12].y)/2;return visible(p[15])&&p[15].y<y||visible(p[16])&&p[16].y<y}).length;return Math.min(1,.35*Math.min(1,valid.length/3)+.65*raised/valid.length)}
function score(now){const p=mainPose();return mode==="heart"?heart(p):mode==="jump"?jump(p,now):mode==="mimic"?mimic(p):mode==="highfive"?highfive():family()}
function recognize(v,now){if(now<cool||capturing){setProgress(0);return}const th=mode==="jump"?.92:.72;if(v>=th){if(!holdAt)holdAt=now;const x=Math.min(1,(now-holdAt)/P[mode].ms);setProgress(x);if(x>=1){success();holdAt=0;setProgress(0)}}else{holdAt=0;setProgress(Math.max(0,(v-.25)/(th-.25))*.5)}}
function success(){cool=performance.now()+4200;effect={type:mode,start:performance.now()};stats.success++;stats.byPose[mode]=(stats.byPose[mode]||0)+1;save("pose_success",{people:poses.length,characters:true});bannerTitle.textContent=P[mode].t;bannerSub.textContent=P[mode].s;banner.classList.add("show");setTimeout(()=>banner.classList.remove("show"),2600);let n=mode==="jump"?1:2;countdown.textContent=n;const t=setInterval(()=>{n--;if(n)countdown.textContent=n;else{clearInterval(t);countdown.textContent="";photo(true)}},650)}
function loop(now){if(!running)return;resize();if(landmarker&&video.readyState>1&&video.currentTime!==lastTime&&now-lastInfer>55){lastTime=video.currentTime;lastInfer=now;try{poses=(landmarker.detectForVideo(video,now).landmarks||[]).filter(p=>area(p)>.01);people.textContent=`${poses.length}명 감지`;recognize(score(now),now)}catch(e){console.warn(e)}}draw(now);requestAnimationFrame(loop)}
function pt(p){return{x:p.x*canvas.width,y:p.y*canvas.height}}
function ease(v){const c1=1.70158,c3=c1+1;return 1+c3*Math.pow(v-1,3)+c1*Math.pow(v-1,2)}
function rr(x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function bubble(text,cx,cy,a=1){ctx.save();ctx.globalAlpha*=a;const f=Math.max(18,canvas.width*.028);ctx.font=`800 ${f}px sans-serif`;const px=f*.8,w=ctx.measureText(text).width+px*2,h=f*2.1,x=Math.max(10,Math.min(canvas.width-w-10,cx-w/2)),y=Math.max(10,cy-h/2);ctx.shadowColor="rgba(0,0,0,.4)";ctx.shadowBlur=18;rr(x,y,w,h,h/2);ctx.fillStyle="rgba(255,247,224,.96)";ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#2a1738";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(text,x+w/2,y+h/2);ctx.restore()}
function character(k,cx,by,th,o={}){const im=chars[k];if(!im?.complete||!im.naturalWidth)return;const enter=Math.min(1,Math.max(0,o.enter??1)),scale=.72+.28*ease(enter),h=th*scale,w=h*im.naturalWidth/im.naturalHeight;ctx.save();ctx.globalAlpha*=o.alpha??1;ctx.translate(cx,by+(o.bob||0));if(o.flip)ctx.scale(-1,1);ctx.shadowColor=o.glow||"rgba(0,0,0,.55)";ctx.shadowBlur=Math.max(12,canvas.width*.025);ctx.drawImage(im,-w/2,-h,w,h);ctx.restore()}
function spark(t,n,colors,up=false){const w=canvas.width,h=canvas.height;ctx.save();ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`${Math.max(24,w*.045)}px sans-serif`;for(let i=0;i<n;i++){const x=(i*83+t*.06*(1+i%3))%w,y=up?h-((i*71+t*.15)%h):(i*67+t*.08)%h;ctx.fillStyle=colors[i%colors.length];ctx.fillText(i%2?"✦":"◆",x,y)}ctx.restore()}
function fx(type,t){const w=canvas.width,h=canvas.height,fade=t<2300?1:Math.max(0,1-(t-2300)/900),enter=Math.min(1,t/420),bob=Math.sin(t/170)*h*.008;ctx.save();ctx.globalAlpha=fade;if(type==="heart"){character("green",w*.79,h*.95,h*.49,{enter,bob,glow:"rgba(255,219,87,.72)"});ctx.font=`${Math.max(38,w*.078)}px serif`;ctx.textAlign="center";ctx.textBaseline="middle";for(let i=0;i<15;i++){const a=i/15*Math.PI*2+t/950,r=w*(.16+.025*Math.sin(t/150+i));ctx.fillStyle=i%2?"#ff79b5":"#ffd95b";ctx.fillText("♥",w*.47+Math.cos(a)*r,h*.36+Math.sin(a)*r*.68)}bubble("LOVE 619!",w*.77,h*.34,fade)}else if(type==="jump"){const lift=Math.sin(Math.min(1,t/900)*Math.PI)*h*.09;character("goggles",w*.22,h*.96-lift,h*.55,{enter,bob,flip:true,glow:"rgba(255,211,77,.76)"});spark(t,24,["#ffd95b","#fff","#8ddcff"],true);bubble("FLY!",w*.22,h*.29-lift*.35,fade)}else if(type==="mimic"){character("zombie",w*.8,h*.96,h*.52,{enter,bob,glow:"rgba(155,104,255,.9)"});ctx.strokeStyle="#c7a9ff";ctx.lineWidth=Math.max(4,w*.007);ctx.setLineDash([18,14]);ctx.lineDashOffset=-t/18;ctx.beginPath();ctx.arc(w*.47,h*.48,Math.min(w,h)*(.26+Math.sin(t/140)*.02),0,Math.PI*2);ctx.stroke();bubble("SYNC 100%",w*.78,h*.33,fade)}else if(type==="highfive"){character("red",w*.15,h*.97,h*.46,{enter,bob,flip:true,glow:"rgba(255,92,79,.72)"});character("green",w*.85,h*.97,h*.46,{enter,bob:-bob,glow:"rgba(255,219,87,.72)"});const c=contact(),cx=c?c.p.x*w:w/2,cy=c?c.p.y*h:h*.38,r=Math.min(w,h)*Math.min(.28,.04+t/4100);ctx.strokeStyle="#ffd95b";ctx.lineWidth=Math.max(5,w*.009);ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();for(let i=0;i<14;i++){const a=i/14*Math.PI*2;ctx.beginPath();ctx.moveTo(cx+Math.cos(a)*r*.6,cy+Math.sin(a)*r*.6);ctx.lineTo(cx+Math.cos(a)*r*1.55,cy+Math.sin(a)*r*1.55);ctx.stroke()}bubble("HIGH FIVE!",w*.5,h*.19,fade)}else{const ks=["red","goggles","green","zombie"],cs=[.14,.37,.63,.86];ks.forEach((k,i)=>character(k,w*cs[i],h*.98,h*(i===1?.36:.33),{enter:Math.max(0,Math.min(1,(t-i*75)/420)),bob:Math.sin(t/180+i)*h*.006,flip:i<2,glow:["#ff5c4f","#ffd34d","#6aff85","#a669ff"][i]}));spark(t,38,["#ffd95b","#9a67ff","#7ff4d5"]);bubble("ANI-ROAD CREW!",w*.5,h*.18,fade)}ctx.restore()}
function draw(now){ctx.clearRect(0,0,canvas.width,canvas.height);if(guide)for(const p of poses){ctx.save();ctx.strokeStyle="rgba(255,218,145,.78)";ctx.lineWidth=Math.max(2,canvas.width/380);ctx.shadowColor="#9467ff";ctx.shadowBlur=10;for(const[a,b]of C)if(visible(p[a])&&visible(p[b])){const x=pt(p[a]),y=pt(p[b]);ctx.beginPath();ctx.moveTo(x.x,x.y);ctx.lineTo(y.x,y.y);ctx.stroke()}ctx.restore()}if(effect&&now-effect.start<3200)fx(effect.type,now-effect.start);else if(effect)effect=null}
function frame(x,w,h){const bh=Math.max(70,h*.105),g=x.createLinearGradient(0,h-bh,w,h);g.addColorStop(0,"rgba(25,14,37,.96)");g.addColorStop(1,"rgba(90,50,145,.94)");x.fillStyle=g;x.fillRect(0,h-bh,w,bh);x.fillStyle="#ffd991";x.font=`900 ${Math.max(24,w*.034)}px sans-serif`;x.textAlign="left";x.textBaseline="middle";x.fillText("순천 애니로드",w*.045,h-bh*.6);x.fillStyle="#fffaf2";x.font=`700 ${Math.max(15,w*.021)}px sans-serif`;x.fillText(`AI 포즈 포토존 · ${P[mode].n} · CHARACTER EDITION`,w*.045,h-bh*.27);x.textAlign="right";x.fillStyle="rgba(255,255,255,.82)";x.font=`700 ${Math.max(13,w*.018)}px sans-serif`;x.fillText(new Date().toLocaleDateString("ko-KR"),w*.955,h-bh*.29)}
async function photo(auto=false){if(!video.videoWidth||capturing)return;capturing=true;capture.disabled=true;try{const p=document.createElement("canvas"),x=p.getContext("2d"),w=video.videoWidth,h=video.videoHeight;p.width=w;p.height=h;if(front){x.translate(w,0);x.scale(-1,1)}x.drawImage(video,0,0,w,h);x.drawImage(canvas,0,0,w,h);x.setTransform(1,0,0,1,0,0);frame(x,w,h);shotBlob=await new Promise(r=>p.toBlob(r,"image/jpeg",.92));if(!shotBlob)throw Error();if(shotUrl)URL.revokeObjectURL(shotUrl);shotUrl=URL.createObjectURL(shotBlob);resultImage.src=shotUrl;stats.captures++;save(auto?"auto_capture":"manual_capture",{people:poses.length,characters:true});resultDialog.showModal()}catch(e){note("사진을 만들지 못했습니다. 다시 시도해주세요.")}finally{capturing=false;capture.disabled=false}}
function download(){if(!shotBlob)return;const u=URL.createObjectURL(shotBlob),a=document.createElement("a");a.href=u;a.download=`aniroad-character-${Date.now()}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);stats.downloads++;save("download")}
async function share(){if(!shotBlob)return;const f=new File([shotBlob],`aniroad-character-${Date.now()}.jpg`,{type:"image/jpeg"});try{if(navigator.share&&navigator.canShare?.({files:[f]})){await navigator.share({title:"순천 애니로드 AI 포즈 포토존",text:"애니로드 캐릭터들과 오늘의 포즈를 완성했어요!",files:[f]});stats.shares++;save("share")}else download()}catch(e){if(e.name!=="AbortError")note("사진 저장을 이용해주세요.")}}
function metrics(){const rate=stats.starts?Math.round(stats.captures/stats.starts*100):0;metricGrid.innerHTML=[[stats.sessions,"접속 세션"],[stats.success,"포즈 성공"],[stats.captures,"사진 생성"],[rate+"%","촬영 전환율"],[stats.shares,"공유"],[stats.downloads,"저장"]].map(v=>`<div class="metric"><strong>${v[0]}</strong><span>${v[1]}</span></div>`).join("");const m=Math.max(1,...Object.values(stats.byPose));poseMetrics.innerHTML=Object.entries(P).map(([k,v])=>`<div class="pose-row"><span>${v.n}</span><div class="pose-bar"><i style="width:${(stats.byPose[k]||0)/m*100}%"></i></div><strong>${stats.byPose[k]||0}</strong></div>`).join("")}
function csv(){const rows=[["time","type","pose","people","characters"],...stats.events.map(e=>[e.time,e.type,e.pose,e.people??"",e.characters??""])],blob=new Blob(["\ufeff"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`aniroad-poc-${Date.now()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
start.onclick=begin;capture.onclick=()=>photo(false);switchBtn.onclick=async()=>{front=!front;switchBtn.disabled=true;try{await startCamera();save("camera_switch")}catch{front=!front;note("카메라 전환에 실패했습니다.")}switchBtn.disabled=false};guideBtn.onclick=()=>{guide=!guide;guideBtn.classList.toggle("active",guide);$("guideFrame").classList.toggle("hidden-guide",!guide)};$("closeResult").onclick=()=>resultDialog.close();$("shareButton").onclick=share;$("downloadButton").onclick=download;$("metricsButton").onclick=()=>{metrics();metricsDialog.showModal()};$("closeMetrics").onclick=()=>metricsDialog.close();$("exportButton").onclick=csv;$("resetMetricsButton").onclick=()=>{if(confirm("이 기기의 PoC 데이터를 초기화할까요?")){stats=fresh();save("reset");metrics()}};window.onresize=resize;window.onbeforeunload=()=>{stream?.getTracks().forEach(t=>t.stop());if(shotUrl)URL.revokeObjectURL(shotUrl)};select("heart",false);
